[phases.setup]
nixPkgs = ["gcc", "stdenv.cc.cc.lib"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install chromium --with-deps"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
